Update auto-manual-ci.yml

diff --git a/.github/workflows/auto-manual-ci.yml b/.github/workflows/auto-manual-ci.yml
--- a/.github/workflows/auto-manual-ci.yml
+++ b/.github/workflows/auto-manual-ci.yml
@@ -6,16 +6,19 @@ on:
       - master
 
 jobs:
-  three_step_workflow:
+  step1:
     runs-on: ubuntu-latest
-
     steps:
       - name: Step 1 - Request to Baidu
         run: |
           curl https://www.baidu.com
-   
+
+  step2:
+    runs-on: ubuntu-latest
+    needs: step1
+    if: github.event_name == 'workflow_dispatch'
+    steps:
       - name: Step 2 - Input env
-        if: github.event_name == 'workflow_dispatch'
         run: |
           read -p "Please input env parameter (test, live, staging): " env
           if [ "$env" != "test" ] && [ "$env" != "live" ] && [ "$env" != "staging" ]; then
@@ -23,7 +26,14 @@ jobs:
             exit 1
           fi
 
+  step3:
+    runs-on: ubuntu-latest
+    needs: step2
+    if: github.event_name == 'workflow_dispatch'
+    steps:
       - name: Step 3 - Input cid
-        if: github.event_name == 'workflow_dispatch'
         run: |
-          echo "Please input cid parameter"
+          read -p "Please input cid parameter: " cid
+          if [ -z "$cid" ]; then
+            echo "CID parameter is required."
+            exit 1
